apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-tomcat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-tomcat
  template:
    metadata:
      labels:
        app: java-tomcat
    spec:
     containers:
        - name: java-tomcat-container
          image: java-tomcat-app:1.0
          ports:
            - containerPort: 8080
